### ISSUE TITLE
web2login的彈跳視窗，Refactor後的錯誤

### ISSUE THREAD

**Issue by hard25670559** [nervina-labs/joyid-sdk-js#18]
### Refactor前的邏輯
[@joyid/evm@0.3.0-beta.0](https://www.npmjs.com/package/@joyid/evm/v/0.3.0-beta.0?activeTab=code)
```typescript
  if (!config.popup) {
    config.popup = openPopup('')

    if (!config.popup) {
      return createBlockDialog(() => connect(uid, config))
    }
  }
```

### Refactor後的邏輯
https://github.com/nervina-labs/joyid-sdk-js/blob/fb1b674af6cce9afb0ef5c078b09c6888137249b/packages/evm/src/web2login.ts#L37-L43

**Comment by yuche** [comment]
try `@joyid/evm@0.3.3`
